<a href="https://colab.research.google.com/github/JyothiAB/Deep-learning/blob/1_Bank-Customer-Churn-Prediction/Bank_customer_churn_prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Dataset for bank customer churn prediction : https://www.kaggle.com/barelydedicated/bank-customer-churn-modeling
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/JyothiAB/Deep-learning/1_Bank-Customer-Churn-Prediction/Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.drop(columns=['RowNumber','Surname','CustomerId'], inplace=True)

In [5]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
df.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [7]:
df.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [8]:
df.describe(include='object')

       Geography Gender
count      10000  10000
unique         3      2
top       France   Male
freq        5014   5457

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[['CreditScore','Age','Tenure','Balance','NumOfProducts','EstimatedSalary']] = scaler.fit_transform(df[['CreditScore','Age','Tenure','Balance','NumOfProducts','EstimatedSalary']])

In [10]:
df.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,0.601058,0.282727,0.501280,0.304848,0.176733,0.70550,0.515100,0.500441,0.203700
std,0.193307,0.141727,0.289217,0.248696,0.193885,0.45584,0.499797,0.287580,0.402769
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,0.468000,0.189189,0.300000,0.000000,0.000000,0.00000,0.000000,0.254977,0.000000
50%,0.604000,0.256757,0.500000,0.387402,0.000000,1.00000,1.000000,0.500960,0.000000
75%,0.736000,0.351351,0.700000,0.508749,0.333333,1.00000,1.000000,0.746955,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000

In [11]:
df['Gender'].replace({'Male':0,'Female':1}, inplace=True)

In [12]:
df['Gender'].describe()

count    10000.000000
mean         0.454300
std          0.497932
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: Gender, dtype: float64

In [13]:
df1 = pd.get_dummies(data = df, columns=['Geography'])

In [14]:
df1.describe()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,0.601058,0.454300,0.282727,0.501280,0.304848,0.176733,0.70550,0.515100,0.500441,0.203700,0.501400,0.250900,0.247700
std,0.193307,0.497932,0.141727,0.289217,0.248696,0.193885,0.45584,0.499797,0.287580,0.402769,0.500023,0.433553,0.431698
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.468000,0.000000,0.189189,0.300000,0.000000,0.000000,0.00000,0.000000,0.254977,0.000000,0.000000,0.000000,0.000000
50%,0.604000,0.000000,0.256757,0.500000,0.387402,0.000000,1.00000,1.000000,0.500960,0.000000,1.000000,0.000000,0.000000
75%,0.736000,1.000000,0.351351,0.700000,0.508749,0.333333,1.00000,1.000000,0.746955,0.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
X = df1.drop(columns = ['Exited'])
y = df1['Exited']

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=5)

In [24]:
len(x_train.columns)

12

In [22]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
                          keras.layers.Dense(12, input_shape = (12,), activation='relu'),
                          keras.layers.Dense(12, input_shape = (6,), activation='relu'),
                          keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(x_train,y_train,epochs = 200)

Epoch 1/200
250/250 [==============================] - 3s 7ms/step - loss: 0.5073 - accuracy: 0.7955
Epoch 2/200
250/250 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 1s 3ms/step - loss: 0.4637 - accuracy: 0.7971
Epoch 4/200
250/250 [==============================] - 1s 3ms/step - loss: 0.4490 - accuracy: 0.8054
Epoch 5/200
250/250 [==============================] - 1s 3ms/step - loss: 0.4329 - accuracy: 0.8119
Epoch 6/200
250/250 [==============================] - 1s 3ms/step - loss: 0.4226 - accuracy: 0.8181
Epoch 7/200
250/250 [==============================] - 1s 3ms/step - loss: 0.4142 - accuracy: 0.8161
Epoch 8/200
250/250 [==============================] - 1s 3ms/step - loss: 0.4079 - accuracy: 0.8214
Epoch 9/200
250/250 [==============================] - 1s 3ms/step - loss: 0.4026 - accuracy: 0.8227
Epoch 10/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3970 - accuracy: 0.8253
Epoch 11/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3934 - accuracy: 0.8270
Epoch 12/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3892 - accuracy: 0.8316
Epoch 13/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3856 - accuracy: 0.8324
Epoch 14/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3821 - accuracy: 0.8324
Epoch 15/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3792 - accuracy: 0.8359
Epoch 16/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3753 - accuracy: 0.8376
Epoch 17/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3716 - accuracy: 0.8411
Epoch 18/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3682 - accuracy: 0.8444
Epoch 19/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3651 - accuracy: 0.8450
Epoch 20/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3631 - accuracy: 0.8466
Epoch 21/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3595 - accuracy: 0.8459
Epoch 22/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3590 - accuracy: 0.8494
Epoch 23/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3559 - accuracy: 0.8497
Epoch 24/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3534 - accuracy: 0.8518
Epoch 25/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3522 - accuracy: 0.8541
Epoch 26/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3507 - accuracy: 0.8546
Epoch 27/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3507 - accuracy: 0.8530
Epoch 28/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3506 - accuracy: 0.8525
Epoch 29/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3491 - accuracy: 0.8568
Epoch 30/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3477 - accuracy: 0.8562
Epoch 31/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3467 - accuracy: 0.8564
Epoch 32/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3468 - accuracy: 0.8566
Epoch 33/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3448 - accuracy: 0.8577
Epoch 34/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3463 - accuracy: 0.8575
Epoch 35/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3433 - accuracy: 0.8608
Epoch 36/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3432 - accuracy: 0.8591
Epoch 37/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3426 - accuracy: 0.8595
Epoch 38/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3426 - accuracy: 0.8594
Epoch 39/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3426 - accuracy: 0.8585
Epoch 40/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3408 - accuracy: 0.8604
Epoch 41/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3410 - accuracy: 0.8626
Epoch 42/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3410 - accuracy: 0.8611
Epoch 43/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3402 - accuracy: 0.8608
Epoch 44/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3380 - accuracy: 0.8614
Epoch 45/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3395 - accuracy: 0.8601
Epoch 46/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3383 - accuracy: 0.8646
Epoch 47/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3368 - accuracy: 0.8643
Epoch 48/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8622
Epoch 49/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3384 - accuracy: 0.8626
Epoch 50/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3376 - accuracy: 0.8634
Epoch 51/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3368 - accuracy: 0.8615
Epoch 52/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3369 - accuracy: 0.8649
Epoch 53/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3374 - accuracy: 0.8640
Epoch 54/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3351 - accuracy: 0.8654
Epoch 55/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3349 - accuracy: 0.8635
Epoch 56/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3366 - accuracy: 0.8630
Epoch 57/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3342 - accuracy: 0.8644
Epoch 58/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3348 - accuracy: 0.8629
Epoch 59/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3344 - accuracy: 0.8641
Epoch 60/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3345 - accuracy: 0.8640
Epoch 61/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3339 - accuracy: 0.8634
Epoch 62/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3335 - accuracy: 0.8643
Epoch 63/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3330 - accuracy: 0.8665
Epoch 64/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8648
Epoch 65/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3329 - accuracy: 0.8661
Epoch 66/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3320 - accuracy: 0.8666
Epoch 67/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3318 - accuracy: 0.8655
Epoch 68/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3320 - accuracy: 0.8669
Epoch 69/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3335 - accuracy: 0.8637
Epoch 70/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3312 - accuracy: 0.8661
Epoch 71/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8650
Epoch 72/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3318 - accuracy: 0.8661
Epoch 73/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8651
Epoch 74/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3317 - accuracy: 0.8662
Epoch 75/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3312 - accuracy: 0.8662
Epoch 76/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3306 - accuracy: 0.8643
Epoch 77/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3309 - accuracy: 0.8659
Epoch 78/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3305 - accuracy: 0.8640
Epoch 79/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3303 - accuracy: 0.8660
Epoch 80/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3297 - accuracy: 0.8658
Epoch 81/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3305 - accuracy: 0.8651
Epoch 82/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3293 - accuracy: 0.8662
Epoch 83/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3295 - accuracy: 0.8661
Epoch 84/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3292 - accuracy: 0.8679
Epoch 85/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3290 - accuracy: 0.8666
Epoch 86/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3291 - accuracy: 0.8659
Epoch 87/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3295 - accuracy: 0.8661
Epoch 88/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3290 - accuracy: 0.8649
Epoch 89/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3282 - accuracy: 0.8648
Epoch 90/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3295 - accuracy: 0.8661
Epoch 91/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3282 - accuracy: 0.8671
Epoch 92/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3283 - accuracy: 0.8640
Epoch 93/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3290 - accuracy: 0.8664
Epoch 94/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3284 - accuracy: 0.8652
Epoch 95/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3280 - accuracy: 0.8670
Epoch 96/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3278 - accuracy: 0.8660
Epoch 97/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3268 - accuracy: 0.8670
Epoch 98/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3270 - accuracy: 0.8675
Epoch 99/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3275 - accuracy: 0.8674
Epoch 100/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3264 - accuracy: 0.8646
Epoch 101/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3266 - accuracy: 0.8684
Epoch 102/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3274 - accuracy: 0.8674
Epoch 103/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3265 - accuracy: 0.8659
Epoch 104/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3267 - accuracy: 0.8668
Epoch 105/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3271 - accuracy: 0.8665
Epoch 106/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3279 - accuracy: 0.8652
Epoch 107/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3268 - accuracy: 0.8666
Epoch 108/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3267 - accuracy: 0.8675
Epoch 109/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3266 - accuracy: 0.8670
Epoch 110/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3268 - accuracy: 0.8636
Epoch 111/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3270 - accuracy: 0.8646
Epoch 112/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3266 - accuracy: 0.8666
Epoch 113/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3251 - accuracy: 0.8686
Epoch 114/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3262 - accuracy: 0.8676
Epoch 115/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3263 - accuracy: 0.8660
Epoch 116/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3256 - accuracy: 0.8679
Epoch 117/200
250/250 [==============================] - 1s 5ms/step - loss: 0.3262 - accuracy: 0.8669
Epoch 118/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3259 - accuracy: 0.8654
Epoch 119/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3259 - accuracy: 0.8673
Epoch 120/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3265 - accuracy: 0.8661
Epoch 121/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3255 - accuracy: 0.8674
Epoch 122/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3252 - accuracy: 0.8674
Epoch 123/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3252 - accuracy: 0.8665
Epoch 124/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3253 - accuracy: 0.8658
Epoch 125/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3249 - accuracy: 0.8662
Epoch 126/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3252 - accuracy: 0.8675
Epoch 127/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3244 - accuracy: 0.8677
Epoch 128/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3252 - accuracy: 0.8668
Epoch 129/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3246 - accuracy: 0.8691
Epoch 130/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3242 - accuracy: 0.8676
Epoch 131/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3252 - accuracy: 0.8669
Epoch 132/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3241 - accuracy: 0.8664
Epoch 133/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3244 - accuracy: 0.8651
Epoch 134/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3242 - accuracy: 0.8691
Epoch 135/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3258 - accuracy: 0.8641
Epoch 136/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3237 - accuracy: 0.8659
Epoch 137/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3252 - accuracy: 0.8671
Epoch 138/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3233 - accuracy: 0.8692
Epoch 139/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3232 - accuracy: 0.8670
Epoch 140/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3241 - accuracy: 0.8659
Epoch 141/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3232 - accuracy: 0.8694
Epoch 142/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3241 - accuracy: 0.8661
Epoch 143/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3240 - accuracy: 0.8677
Epoch 144/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3233 - accuracy: 0.8655
Epoch 145/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3232 - accuracy: 0.8675
Epoch 146/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3226 - accuracy: 0.8664
Epoch 147/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3239 - accuracy: 0.8674
Epoch 148/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3227 - accuracy: 0.8655
Epoch 149/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3233 - accuracy: 0.8686
Epoch 150/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3224 - accuracy: 0.8671
Epoch 151/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3234 - accuracy: 0.8681
Epoch 152/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3238 - accuracy: 0.8674
Epoch 153/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3226 - accuracy: 0.8664
Epoch 154/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3230 - accuracy: 0.8658
Epoch 155/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3235 - accuracy: 0.8659
Epoch 156/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3226 - accuracy: 0.8683
Epoch 157/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3230 - accuracy: 0.8680
Epoch 158/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3227 - accuracy: 0.8683
Epoch 159/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3231 - accuracy: 0.8661
Epoch 160/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3222 - accuracy: 0.8656
Epoch 161/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3216 - accuracy: 0.8674
Epoch 162/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3227 - accuracy: 0.8668
Epoch 163/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3225 - accuracy: 0.8694
Epoch 164/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3230 - accuracy: 0.8690
Epoch 165/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3221 - accuracy: 0.8679
Epoch 166/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3227 - accuracy: 0.8661
Epoch 167/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3218 - accuracy: 0.8668
Epoch 168/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3222 - accuracy: 0.8676
Epoch 169/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3226 - accuracy: 0.8664
Epoch 170/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3216 - accuracy: 0.8658
Epoch 171/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3226 - accuracy: 0.8650
Epoch 172/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3216 - accuracy: 0.8660
Epoch 173/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3217 - accuracy: 0.8681
Epoch 174/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3223 - accuracy: 0.8646
Epoch 175/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3215 - accuracy: 0.8676
Epoch 176/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3215 - accuracy: 0.8685
Epoch 177/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3216 - accuracy: 0.8660
Epoch 178/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3214 - accuracy: 0.8686
Epoch 179/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3221 - accuracy: 0.8661
Epoch 180/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3217 - accuracy: 0.8661
Epoch 181/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3215 - accuracy: 0.8684
Epoch 182/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3213 - accuracy: 0.8684
Epoch 183/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3210 - accuracy: 0.8681
Epoch 184/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3206 - accuracy: 0.8676
Epoch 185/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3212 - accuracy: 0.8675
Epoch 186/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3210 - accuracy: 0.8676
Epoch 187/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3211 - accuracy: 0.8660
Epoch 188/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3225 - accuracy: 0.8674
Epoch 189/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3220 - accuracy: 0.8668
Epoch 190/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3223 - accuracy: 0.8680
Epoch 191/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3208 - accuracy: 0.8676
Epoch 192/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3222 - accuracy: 0.8686
Epoch 193/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3213 - accuracy: 0.8680
Epoch 194/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3205 - accuracy: 0.8689
Epoch 195/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3212 - accuracy: 0.8683
Epoch 196/200

In [23]:
model.compile(optimizer='SGD',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(x_train,y_train,epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 5ms/step - loss: 0.3210 - accuracy: 0.8660
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3209 - accuracy: 0.8670
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8666
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8669
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3202 - accuracy: 0.8696
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3205 - accuracy: 0.8677
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8676
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3203 - accuracy: 0.8692
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3203 - accuracy: 0.8691
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8687
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3209 - accuracy: 0.8675
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3208 - accuracy: 0.8671
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8673
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3204 - accuracy: 0.8687
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8670
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3195 - accuracy: 0.8681
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3205 - accuracy: 0.8671
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3206 - accuracy: 0.8662
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3200 - accuracy: 0.8679
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8680
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3189 - accuracy: 0.8685
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3193 - accuracy: 0.8681
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3205 - accuracy: 0.8681
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3209 - accuracy: 0.8677
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3197 - accuracy: 0.8689
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3200 - accuracy: 0.8668
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3203 - accuracy: 0.8681
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3206 - accuracy: 0.8675
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3194 - accuracy: 0.8676
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8684
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8679
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3203 - accuracy: 0.8669
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8673
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8685
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8677
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3200 - accuracy: 0.8694
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3188 - accuracy: 0.8716
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3193 - accuracy: 0.8691
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3196 - accuracy: 0.8658
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8659
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3207 - accuracy: 0.8662
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8669
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3202 - accuracy: 0.8664
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8670
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3192 - accuracy: 0.8679
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8666
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8692
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8684
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3195 - accuracy: 0.8677
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3193 - accuracy: 0.8674
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3194 - accuracy: 0.8665
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3203 - accuracy: 0.8680
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3197 - accuracy: 0.8671
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3197 - accuracy: 0.8670
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3195 - accuracy: 0.8695
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3204 - accuracy: 0.8687
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8681
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3200 - accuracy: 0.8679
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3202 - accuracy: 0.8658
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8660
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3200 - accuracy: 0.8668
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8684
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8675
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8671
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3205 - accuracy: 0.8670
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3204 - accuracy: 0.8690
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3191 - accuracy: 0.8686
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3195 - accuracy: 0.8680
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8683
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8674
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3204 - accuracy: 0.8677
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8670
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3194 - accuracy: 0.8681
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3194 - accuracy: 0.8689
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8656
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8691
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3190 - accuracy: 0.8675
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3194 - accuracy: 0.8668
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3192 - accuracy: 0.8674
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8669
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8675
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3194 - accuracy: 0.8691
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3203 - accuracy: 0.8668
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8677
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8681
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3193 - accuracy: 0.8684
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3199 - accuracy: 0.8680
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8670
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3197 - accuracy: 0.8680
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3200 - accuracy: 0.8689
Epoch 91/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8679
Epoch 92/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3194 - accuracy: 0.8675
Epoch 93/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3193 - accuracy: 0.8686
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3187 - accuracy: 0.8694
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3194 - accuracy: 0.8669
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3192 - accuracy: 0.8670
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3192 - accuracy: 0.8690
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3191 - accuracy: 0.8702
Epoch 99/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3191 - accuracy: 0.8681
Epoch 100/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3187 - accuracy: 0.8677

In [25]:
model.evaluate(x_test,y_test)

63/63 [==============================] - 1s 5ms/step - loss: 0.3446 - accuracy: 0.8600

[0.3445870280265808, 0.8600000143051147]

In [30]:
y_pred = model.predict(x_test)
y_pred

array([[0.05764392],
       [0.06791589],
       [0.0512576 ],
       ...,
       [0.02203725],
       [0.03229055],
       [0.06185446]], dtype=float32)

In [32]:
y_predict = []
for i in y_pred:
  if i < 0.5:
    y_predict.append(0)
  else:
    y_predict.append(1)

In [33]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1595
           1       0.75      0.46      0.57       405

    accuracy                           0.86      2000
   macro avg       0.81      0.71      0.74      2000
weighted avg       0.85      0.86      0.85      2000

In [34]:
print(confusion_matrix(y_test,y_predict))

[[1533   62]
 [ 218  187]]